import type { ClaudeClient } from "../../ai/fixSuggester.js";
import type { AISuggestion, ParsedBlock } from "../../types/index.js";

/**
 * Creates a plausible deterministic mock suggestion.
 * @param block Failing parsed block.
 * @param error Runtime error text.
 * @returns Mock AI suggestion.
 */
export function mockAISuggestion(
  block: ParsedBlock,
  error: string,
): AISuggestion {
  return {
    diagnosis: `Mock: fix the ${block.language} failure: ${error.split("\n")[0] ?? "unknown error"}`,
    fixedCode: `# Mock fix for ${block.language} block\n${block.code}`,
    note: "This is a mock response for testing",
  };
}

/**
 * Creates a Claude client that returns one structured mock response.
 * @param suggestion Suggestion returned by the mock.
 * @param onRequest Optional callback for request assertions.
 * @returns Network-free Claude client.
 */
export function createClaudeMock(
  suggestion: AISuggestion,
  onRequest?: ((prompt: string) => void) | undefined,
): ClaudeClient {
  return {
    /**
     * Returns a structured mock Claude response.
     * @param prompt Prompt generated by DocRunner.
     * @returns Structured mock response text.
     */
    async request(prompt: string): Promise<string> {
      onRequest?.(prompt);
      return [
        `DIAGNOSIS: ${suggestion.diagnosis}`,
        "FIXED_CODE:",
        "```text",
        suggestion.fixedCode,
        "```",
        `NOTE: ${suggestion.note ?? ""}`,
      ].join("\n");
    },
  };
}
